= Java logic description - Styleguide ( to VHDL)
:toc:
:toclevels: 4
:sectnums:
:sectlinks:
:max-width: 52em
:prewrap!:
:cpp: C++
:cp: C/++
:wildcard: *


== Approach

This styleguide is for describing and testing hardware logic in Java. 

The approach can be seen similar as usage {cpp} for the same,
for example described in the german article:
link:https://www.elektronikpraxis.vogel.de/fpgas-mit-cc-programmieren-herausforderungen-bei-hls-design-flows-a-826858/[]

But the {cpp} to VHDL approach seems to be very complex, powerful, but also difficult to handle. 
In opposite this Java to VHDL approach is only for simulation simple hardware logic and getting the VHDL code.

In opposite to VHDL Java is more known, also may be for hardware oriented people.
Java allows with its own infrastructure to deal with different input stimuli possibilities
and evaluation of test results. It runs without additional effort. Only a typically Java development system
such as Eclipse is necessary.

The solution for simulation hardware is related to only clocked synchronous logic. 
One clock edge actualize the state (Q on FF), which is prepared before (D input on FF).
The preparation is done with a new instance of the so named process classes.


== Test environment

The test environment can be free programmed in Java using all capabilities,
for example reading test stimuli data from Excel sheets or other result files.

== top level class

The top level class may be one only for simulation, or one for the VHDL FPGA design. 

In both cases modules are defined which are found in other Java classes respectively Java files.


== Module inner class, sub modules

Any class, especially the top level class but also all module class can contain

----
//in class test/java/org/vishia/spehw/Test_SpiSlave_Fpga.java:
include::../../../test/java/org/vishia/spehw/Test_SpiSlave_Fpga.java[tag=classhead]
include::../../../test/java/org/vishia/spehw/Test_SpiSlave_Fpga.java[tag=Modules]
----

Ones of the importance is: You can have more as one module (instance name) 
with the same type (Class name). Any module instance will be placed also in the FPGA.
But of course the java file of the class is only parsed once. 


== Meaning of In and Out inner classes

The top level module(s) can have In and Out classes which defines the signals on the Pins of the FPGA.

If inner modules have In and Out inner classes, then it depends on the implementation strategy in VHDL:

* If one VHDL file for the module is generated, it is the interface of this VHDL module. 

* If the module is used flattened in the enclosing module, 
then specific Records for this `In` and `Out` inner classes are created. 
The values are gotten and taken there. 
But the enclosing module is responsible to set content to In and put content from out. 


== Meaning of Ref inner class

A `Ref` class can only be used if this module should be generated flattened in VHDL.
But this is an important feature which simlifies the design. 

The idea of references is usual known in ObjectOrientation programming. 
References are __associations__, __aggregations__ or __compositions__ (UML slang),
whereas __associations__ are flexible. That cannot be used for a FPGA design.
But __aggregations__ (relations to another module given on startup) 
or __compositions__ (relations to own inner modules built on startup) are sensible and possible.

The __compositions__ are given with the inner class `Module`, see chapter above.

The inner class `Ref` contains references to other modules outside, which are reachable
in the flattened FPGA, FlipFlops of other modules. 
They can be used immediately of course in the FPGA (direct lines) 
but also for a modular hardware design in Java. 

In VHDL such referencing is not provided. 
All signals should be connected (laboriously) via the inputs and the outputs of the modules. 
VHDL does non know the referencing approach of the ObjectOrientation programming. 
But the modularity is given by referencing. 
The only ambiguity is: Referencing builds a dependency to the referenced module;
the referenced module should be known. It is not independent.

For this question, the ObjectOrientation have an answer: Interfacing. 
In Java you can use `interface` for a module, access via the `interface` type via the reference. 
Then you can connect different types of modules with the same given reference type.
This is especially necessary and proper for a test environment of a module.
You can replace the originally referenced module type with a so named "__Mock__",
which delivers the signals for test and check the delivered results.

This same approach is possible in a flattened VHDL design. 


== Execution order

The interface

----
include::../../../main/java/srcJava_vishiaBase/org/vishia/fpga/FpgaModule_ifc.java[tag=classhead]
include::../../../main/java/srcJava_vishiaBase/org/vishia/fpga/FpgaModule_ifc.java[tag=body]
----

defines this two basically operations. This interface should be implemented by all modules,
also the top level. Then it is unique which should be called, for example in

=== In the top level

Execute modules

----
//in class test/java/org/vishia/spehw/Test_SpiSlave_Fpga.java:
include::../../../test/java/org/vishia/spehw/Test_SpiSlave_Fpga.java[tag=stepupdate]
----

This is the functionality for one clock in the FPGA. If you need more clocks,
then more manually defined step and update functions are necessary. 
Note that using one clock is often the best decision, you should synchronize all signals
to this one clock. But that is special knowledge of hardware FPGA design, not deeply explained here.


[#execModule]
=== In a module

Execute processes

----
//in class test/java/org/vishia/spehw/SpiSlave.java:
include::../../../test/java/org/vishia/spehw/SpiSlave.java[tag=step]
----

In this example the `Sh` is an inner class of this module, it builds one process.
The new state of the process is calculated in the constructor `Sh(...)`
but firstly only temporary stored. 
Because: All other processes should not use the new value of this, 
they should use before the clock edge the current ones. 

The constructor of the process should get the following arguments:

* `time`: The currently central time of this step for timing assertions.
* `this.sh` This is the current state of this process itself. 
  Its inner argument name is `z` as in Z-Transformation controlling theory.
* `this`: The reference of the module, the environment class instance. 
  Its inner argument name is `mdl`, shortly for __module__.
  
Note that the inner class for the Process should be `static`. 
It means this inner class is independent of the environment, the module class. 
It has no access. The other possibility in Java is: using a non `static` class
which knows its environment. But this is lesser obviously. 
The style guide decision is: Using a explicit reference named `mdl`.

The update operation looks like:

----
//in class test/java/org/vishia/spehw/SpiSlave.java:
include::../../../test/java/org/vishia/spehw/SpiSlave.java[tag=update]
----

It also transports values from the process(es) out to the `out` structure,
which is not clocked, immediately assigned (from clocked inner signals) to the pins. 

Shortly to the writing style with `this.`: This is also possible in {cpp} writing `this->`.
But in the early days of enthusiasm for the new class-oriented operations
it was recommended to leave the `thiz->` designations for instance variable defined on class level.
Meanwhile also in {cpp} but especially as style guide in Java 
it is partially recommended to write `this.` in Java or `this->` in {cpp}.
Why: It is more obviously that an instance variable is used. 
Writing errors (confusion with arguments and stack variables) are prevented.
The effort for writing the `this.` is properly minimized using auto completion while editing. 
The Java2Vhdl converter supports both, writing with `this.` or without. 

== Process classes

=== Data definition

In an example design 

----
//in class test/java/org/vishia/spehw/SpiSlave.java:
include::../../../test/java/org/vishia/spehw/SpiSlave.java[tag=ProcessClassHead]
----

this inner static class is declared with final members.
The `final` keyword assures that any data member is handled unique and obviously. 
It is a helper for thinking the logic.

If you can see the annotation `@Fpga.BITVECTOR(17)` defines that 17 bits should be used,
implemented in VHDL as

----
TYPE SpiSlave_Sh_REC IS RECORD
  shData : BIT_VECTOR(16 DOWNTO 0);
  wrData : BIT_VECTOR(15 DOWNTO 0);
  spiClkQ1 : BIT;
----

as well as the `spiClkQ1` as simple logical signal.

Also the 

----
  ctBits : STD_LOGIC_VECTOR(4 DOWNTO 0);
  ctWords : STD_LOGIC_VECTOR(8 DOWNTO 0);
----

is supported. The variables `_time_` and `m_...` doesn't have a representation in VHDL,
there are only for Java test organization. For `_time_` see chapter <<#timecheck>>

=== Execution

The call of execution of one process is written in Java in the step routine:

----
//in class test/java/org/vishia/spehw/SpiSlave.java:
include::../../../test/java/org/vishia/spehw/SpiSlave.java[tag=step]
----

As you see a new instance is created. Handling with allocated memory in Java is fast, no discussion necessary.

The new instance is stored previously as `sh_d` and with the 

----
//in class test/java/org/vishia/spehw/SpiSlave.java:
include::../../../test/java/org/vishia/spehw/SpiSlave.java[tag=update]
----

established as new state, see also chapter <<#execModule>>

The constructor code contains the VHDL `PROCESS` code:

----
//in class test/java/org/vishia/spehw/SpiSlave.java:
include::../../../test/java/org/vishia/spehw/SpiSlave.java[tag=ctorSh]
----

See also next chapter

[#VhdlConvOps]
== Special operations for bit vectors

This operations are static in class VhdlConv for the Java simulation.
For the VHDL code it is translated as specials:

TODO

This 


[#timecheck]
== Checking time between FF groups

TODO assertion on Java, generation of timeing constrains for VHDL